// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: album.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAlbumArtist = `-- name: AddAlbumArtist :exec
INSERT INTO album_artists (album_id, artist_id, role, sub_role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (artist_id, album_id, role, sub_role) DO NOTHING
`

type AddAlbumArtistParams struct {
	AlbumID  string `json:"album_id"`
	ArtistID string `json:"artist_id"`
	Role     string `json:"role"`
	SubRole  string `json:"sub_role"`
}

func (q *Queries) AddAlbumArtist(ctx context.Context, arg AddAlbumArtistParams) error {
	_, err := q.db.Exec(ctx, addAlbumArtist,
		arg.AlbumID,
		arg.ArtistID,
		arg.Role,
		arg.SubRole,
	)
	return err
}

const countAlbums = `-- name: CountAlbums :one
SELECT count(*) FROM album
WHERE missing = FALSE
`

func (q *Queries) CountAlbums(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAlbums)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM album
WHERE id = $1
`

func (q *Queries) DeleteAlbum(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAlbum, id)
	return err
}

const getAlbumArtists = `-- name: GetAlbumArtists :many
SELECT aa.album_id, aa.artist_id, aa.role, aa.sub_role, a.name as artist_name FROM album_artists aa
JOIN artist a ON aa.artist_id = a.id
WHERE aa.album_id = $1
`

type GetAlbumArtistsRow struct {
	AlbumID    string `json:"album_id"`
	ArtistID   string `json:"artist_id"`
	Role       string `json:"role"`
	SubRole    string `json:"sub_role"`
	ArtistName string `json:"artist_name"`
}

func (q *Queries) GetAlbumArtists(ctx context.Context, albumID string) ([]GetAlbumArtistsRow, error) {
	rows, err := q.db.Query(ctx, getAlbumArtists, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumArtistsRow
	for rows.Next() {
		var i GetAlbumArtistsRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.ArtistID,
			&i.Role,
			&i.SubRole,
			&i.ArtistName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumByID = `-- name: GetAlbumByID :one
SELECT id, library_id, name, artist_id, artist, album_artist, album_artist_id, embed_art_path, cover_art_path, cover_art_id, max_year, min_year, date, max_original_year, min_original_year, original_date, release_date, compilation, comment, song_count, duration, size, discs, sort_album_name, sort_album_artist_name, order_album_name, order_album_artist_name, catalog_num, mbz_album_id, mbz_album_artist_id, mbz_album_type, mbz_album_comment, mbz_release_group_id, folder_ids, explicit_status, rg_album_gain, rg_album_peak, description, small_image_url, medium_image_url, large_image_url, external_url, external_info_updated_at, genre, tags, missing, imported_at, created_at, updated_at FROM album
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAlbumByID(ctx context.Context, id string) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByID, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.ArtistID,
		&i.Artist,
		&i.AlbumArtist,
		&i.AlbumArtistID,
		&i.EmbedArtPath,
		&i.CoverArtPath,
		&i.CoverArtID,
		&i.MaxYear,
		&i.MinYear,
		&i.Date,
		&i.MaxOriginalYear,
		&i.MinOriginalYear,
		&i.OriginalDate,
		&i.ReleaseDate,
		&i.Compilation,
		&i.Comment,
		&i.SongCount,
		&i.Duration,
		&i.Size,
		&i.Discs,
		&i.SortAlbumName,
		&i.SortAlbumArtistName,
		&i.OrderAlbumName,
		&i.OrderAlbumArtistName,
		&i.CatalogNum,
		&i.MbzAlbumID,
		&i.MbzAlbumArtistID,
		&i.MbzAlbumType,
		&i.MbzAlbumComment,
		&i.MbzReleaseGroupID,
		&i.FolderIds,
		&i.ExplicitStatus,
		&i.RgAlbumGain,
		&i.RgAlbumPeak,
		&i.Description,
		&i.SmallImageUrl,
		&i.MediumImageUrl,
		&i.LargeImageUrl,
		&i.ExternalUrl,
		&i.ExternalInfoUpdatedAt,
		&i.Genre,
		&i.Tags,
		&i.Missing,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlbums = `-- name: ListAlbums :many
SELECT id, library_id, name, artist_id, artist, album_artist, album_artist_id, embed_art_path, cover_art_path, cover_art_id, max_year, min_year, date, max_original_year, min_original_year, original_date, release_date, compilation, comment, song_count, duration, size, discs, sort_album_name, sort_album_artist_name, order_album_name, order_album_artist_name, catalog_num, mbz_album_id, mbz_album_artist_id, mbz_album_type, mbz_album_comment, mbz_release_group_id, folder_ids, explicit_status, rg_album_gain, rg_album_peak, description, small_image_url, medium_image_url, large_image_url, external_url, external_info_updated_at, genre, tags, missing, imported_at, created_at, updated_at FROM album
WHERE missing = FALSE
ORDER BY sort_album_name ASC, name ASC
LIMIT $1 OFFSET $2
`

type ListAlbumsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAlbums(ctx context.Context, arg ListAlbumsParams) ([]Album, error) {
	rows, err := q.db.Query(ctx, listAlbums, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.ArtistID,
			&i.Artist,
			&i.AlbumArtist,
			&i.AlbumArtistID,
			&i.EmbedArtPath,
			&i.CoverArtPath,
			&i.CoverArtID,
			&i.MaxYear,
			&i.MinYear,
			&i.Date,
			&i.MaxOriginalYear,
			&i.MinOriginalYear,
			&i.OriginalDate,
			&i.ReleaseDate,
			&i.Compilation,
			&i.Comment,
			&i.SongCount,
			&i.Duration,
			&i.Size,
			&i.Discs,
			&i.SortAlbumName,
			&i.SortAlbumArtistName,
			&i.OrderAlbumName,
			&i.OrderAlbumArtistName,
			&i.CatalogNum,
			&i.MbzAlbumID,
			&i.MbzAlbumArtistID,
			&i.MbzAlbumType,
			&i.MbzAlbumComment,
			&i.MbzReleaseGroupID,
			&i.FolderIds,
			&i.ExplicitStatus,
			&i.RgAlbumGain,
			&i.RgAlbumPeak,
			&i.Description,
			&i.SmallImageUrl,
			&i.MediumImageUrl,
			&i.LargeImageUrl,
			&i.ExternalUrl,
			&i.ExternalInfoUpdatedAt,
			&i.Genre,
			&i.Tags,
			&i.Missing,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlbumsByArtist = `-- name: ListAlbumsByArtist :many
SELECT id, library_id, name, artist_id, artist, album_artist, album_artist_id, embed_art_path, cover_art_path, cover_art_id, max_year, min_year, date, max_original_year, min_original_year, original_date, release_date, compilation, comment, song_count, duration, size, discs, sort_album_name, sort_album_artist_name, order_album_name, order_album_artist_name, catalog_num, mbz_album_id, mbz_album_artist_id, mbz_album_type, mbz_album_comment, mbz_release_group_id, folder_ids, explicit_status, rg_album_gain, rg_album_peak, description, small_image_url, medium_image_url, large_image_url, external_url, external_info_updated_at, genre, tags, missing, imported_at, created_at, updated_at FROM album
WHERE (artist_id = $1 OR album_artist_id = $1) AND missing = FALSE
ORDER BY min_year DESC, name ASC
`

func (q *Queries) ListAlbumsByArtist(ctx context.Context, artistID string) ([]Album, error) {
	rows, err := q.db.Query(ctx, listAlbumsByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.Name,
			&i.ArtistID,
			&i.Artist,
			&i.AlbumArtist,
			&i.AlbumArtistID,
			&i.EmbedArtPath,
			&i.CoverArtPath,
			&i.CoverArtID,
			&i.MaxYear,
			&i.MinYear,
			&i.Date,
			&i.MaxOriginalYear,
			&i.MinOriginalYear,
			&i.OriginalDate,
			&i.ReleaseDate,
			&i.Compilation,
			&i.Comment,
			&i.SongCount,
			&i.Duration,
			&i.Size,
			&i.Discs,
			&i.SortAlbumName,
			&i.SortAlbumArtistName,
			&i.OrderAlbumName,
			&i.OrderAlbumArtistName,
			&i.CatalogNum,
			&i.MbzAlbumID,
			&i.MbzAlbumArtistID,
			&i.MbzAlbumType,
			&i.MbzAlbumComment,
			&i.MbzReleaseGroupID,
			&i.FolderIds,
			&i.ExplicitStatus,
			&i.RgAlbumGain,
			&i.RgAlbumPeak,
			&i.Description,
			&i.SmallImageUrl,
			&i.MediumImageUrl,
			&i.LargeImageUrl,
			&i.ExternalUrl,
			&i.ExternalInfoUpdatedAt,
			&i.Genre,
			&i.Tags,
			&i.Missing,
			&i.ImportedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAlbum = `-- name: UpsertAlbum :one
INSERT INTO album (
    id, library_id, name, artist_id, artist, album_artist, album_artist_id,
    embed_art_path, cover_art_path, cover_art_id, max_year, min_year, date,
    max_original_year, min_original_year, original_date, release_date,
    compilation, comment, song_count, duration, size, discs,
    sort_album_name, sort_album_artist_name, order_album_name, order_album_artist_name,
    catalog_num, mbz_album_id, mbz_album_artist_id, mbz_album_type, mbz_album_comment,
    mbz_release_group_id, folder_ids, explicit_status, rg_album_gain, rg_album_peak,
    description, small_image_url, medium_image_url, large_image_url, external_url,
    external_info_updated_at, genre, tags, missing, imported_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20, $21, $22, $23,
    $24, $25, $26, $27,
    $28, $29, $30, $31, $32,
    $33, $34, $35, $36, $37,
    $38, $39, $40, $41, $42,
    $43, $44, $45, $46, $47, $48, $49
)
ON CONFLICT (id) DO UPDATE SET
    library_id = EXCLUDED.library_id,
    name = EXCLUDED.name,
    artist_id = EXCLUDED.artist_id,
    artist = EXCLUDED.artist,
    album_artist = EXCLUDED.album_artist,
    album_artist_id = EXCLUDED.album_artist_id,
    embed_art_path = EXCLUDED.embed_art_path,
    cover_art_path = EXCLUDED.cover_art_path,
    cover_art_id = EXCLUDED.cover_art_id,
    max_year = EXCLUDED.max_year,
    min_year = EXCLUDED.min_year,
    date = EXCLUDED.date,
    max_original_year = EXCLUDED.max_original_year,
    min_original_year = EXCLUDED.min_original_year,
    original_date = EXCLUDED.original_date,
    release_date = EXCLUDED.release_date,
    compilation = EXCLUDED.compilation,
    comment = EXCLUDED.comment,
    song_count = EXCLUDED.song_count,
    duration = EXCLUDED.duration,
    size = EXCLUDED.size,
    discs = EXCLUDED.discs,
    sort_album_name = EXCLUDED.sort_album_name,
    sort_album_artist_name = EXCLUDED.sort_album_artist_name,
    order_album_name = EXCLUDED.order_album_name,
    order_album_artist_name = EXCLUDED.order_album_artist_name,
    catalog_num = EXCLUDED.catalog_num,
    mbz_album_id = EXCLUDED.mbz_album_id,
    mbz_album_artist_id = EXCLUDED.mbz_album_artist_id,
    mbz_album_type = EXCLUDED.mbz_album_type,
    mbz_album_comment = EXCLUDED.mbz_album_comment,
    mbz_release_group_id = EXCLUDED.mbz_release_group_id,
    folder_ids = EXCLUDED.folder_ids,
    explicit_status = EXCLUDED.explicit_status,
    rg_album_gain = EXCLUDED.rg_album_gain,
    rg_album_peak = EXCLUDED.rg_album_peak,
    description = EXCLUDED.description,
    small_image_url = EXCLUDED.small_image_url,
    medium_image_url = EXCLUDED.medium_image_url,
    large_image_url = EXCLUDED.large_image_url,
    external_url = EXCLUDED.external_url,
    external_info_updated_at = EXCLUDED.external_info_updated_at,
    genre = EXCLUDED.genre,
    tags = EXCLUDED.tags,
    missing = EXCLUDED.missing,
    imported_at = EXCLUDED.imported_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, library_id, name, artist_id, artist, album_artist, album_artist_id, embed_art_path, cover_art_path, cover_art_id, max_year, min_year, date, max_original_year, min_original_year, original_date, release_date, compilation, comment, song_count, duration, size, discs, sort_album_name, sort_album_artist_name, order_album_name, order_album_artist_name, catalog_num, mbz_album_id, mbz_album_artist_id, mbz_album_type, mbz_album_comment, mbz_release_group_id, folder_ids, explicit_status, rg_album_gain, rg_album_peak, description, small_image_url, medium_image_url, large_image_url, external_url, external_info_updated_at, genre, tags, missing, imported_at, created_at, updated_at
`

type UpsertAlbumParams struct {
	ID                    string             `json:"id"`
	LibraryID             int32              `json:"library_id"`
	Name                  string             `json:"name"`
	ArtistID              string             `json:"artist_id"`
	Artist                string             `json:"artist"`
	AlbumArtist           string             `json:"album_artist"`
	AlbumArtistID         string             `json:"album_artist_id"`
	EmbedArtPath          string             `json:"embed_art_path"`
	CoverArtPath          string             `json:"cover_art_path"`
	CoverArtID            string             `json:"cover_art_id"`
	MaxYear               int32              `json:"max_year"`
	MinYear               int32              `json:"min_year"`
	Date                  string             `json:"date"`
	MaxOriginalYear       int32              `json:"max_original_year"`
	MinOriginalYear       int32              `json:"min_original_year"`
	OriginalDate          string             `json:"original_date"`
	ReleaseDate           string             `json:"release_date"`
	Compilation           bool               `json:"compilation"`
	Comment               string             `json:"comment"`
	SongCount             int32              `json:"song_count"`
	Duration              float32            `json:"duration"`
	Size                  int64              `json:"size"`
	Discs                 string             `json:"discs"`
	SortAlbumName         string             `json:"sort_album_name"`
	SortAlbumArtistName   string             `json:"sort_album_artist_name"`
	OrderAlbumName        string             `json:"order_album_name"`
	OrderAlbumArtistName  string             `json:"order_album_artist_name"`
	CatalogNum            string             `json:"catalog_num"`
	MbzAlbumID            string             `json:"mbz_album_id"`
	MbzAlbumArtistID      string             `json:"mbz_album_artist_id"`
	MbzAlbumType          string             `json:"mbz_album_type"`
	MbzAlbumComment       string             `json:"mbz_album_comment"`
	MbzReleaseGroupID     string             `json:"mbz_release_group_id"`
	FolderIds             string             `json:"folder_ids"`
	ExplicitStatus        string             `json:"explicit_status"`
	RgAlbumGain           *float64           `json:"rg_album_gain"`
	RgAlbumPeak           *float64           `json:"rg_album_peak"`
	Description           string             `json:"description"`
	SmallImageUrl         string             `json:"small_image_url"`
	MediumImageUrl        string             `json:"medium_image_url"`
	LargeImageUrl         string             `json:"large_image_url"`
	ExternalUrl           string             `json:"external_url"`
	ExternalInfoUpdatedAt pgtype.Timestamptz `json:"external_info_updated_at"`
	Genre                 string             `json:"genre"`
	Tags                  string             `json:"tags"`
	Missing               bool               `json:"missing"`
	ImportedAt            pgtype.Timestamptz `json:"imported_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAlbum(ctx context.Context, arg UpsertAlbumParams) (Album, error) {
	row := q.db.QueryRow(ctx, upsertAlbum,
		arg.ID,
		arg.LibraryID,
		arg.Name,
		arg.ArtistID,
		arg.Artist,
		arg.AlbumArtist,
		arg.AlbumArtistID,
		arg.EmbedArtPath,
		arg.CoverArtPath,
		arg.CoverArtID,
		arg.MaxYear,
		arg.MinYear,
		arg.Date,
		arg.MaxOriginalYear,
		arg.MinOriginalYear,
		arg.OriginalDate,
		arg.ReleaseDate,
		arg.Compilation,
		arg.Comment,
		arg.SongCount,
		arg.Duration,
		arg.Size,
		arg.Discs,
		arg.SortAlbumName,
		arg.SortAlbumArtistName,
		arg.OrderAlbumName,
		arg.OrderAlbumArtistName,
		arg.CatalogNum,
		arg.MbzAlbumID,
		arg.MbzAlbumArtistID,
		arg.MbzAlbumType,
		arg.MbzAlbumComment,
		arg.MbzReleaseGroupID,
		arg.FolderIds,
		arg.ExplicitStatus,
		arg.RgAlbumGain,
		arg.RgAlbumPeak,
		arg.Description,
		arg.SmallImageUrl,
		arg.MediumImageUrl,
		arg.LargeImageUrl,
		arg.ExternalUrl,
		arg.ExternalInfoUpdatedAt,
		arg.Genre,
		arg.Tags,
		arg.Missing,
		arg.ImportedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.Name,
		&i.ArtistID,
		&i.Artist,
		&i.AlbumArtist,
		&i.AlbumArtistID,
		&i.EmbedArtPath,
		&i.CoverArtPath,
		&i.CoverArtID,
		&i.MaxYear,
		&i.MinYear,
		&i.Date,
		&i.MaxOriginalYear,
		&i.MinOriginalYear,
		&i.OriginalDate,
		&i.ReleaseDate,
		&i.Compilation,
		&i.Comment,
		&i.SongCount,
		&i.Duration,
		&i.Size,
		&i.Discs,
		&i.SortAlbumName,
		&i.SortAlbumArtistName,
		&i.OrderAlbumName,
		&i.OrderAlbumArtistName,
		&i.CatalogNum,
		&i.MbzAlbumID,
		&i.MbzAlbumArtistID,
		&i.MbzAlbumType,
		&i.MbzAlbumComment,
		&i.MbzReleaseGroupID,
		&i.FolderIds,
		&i.ExplicitStatus,
		&i.RgAlbumGain,
		&i.RgAlbumPeak,
		&i.Description,
		&i.SmallImageUrl,
		&i.MediumImageUrl,
		&i.LargeImageUrl,
		&i.ExternalUrl,
		&i.ExternalInfoUpdatedAt,
		&i.Genre,
		&i.Tags,
		&i.Missing,
		&i.ImportedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
