// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: annotation.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAnnotation = `-- name: GetAnnotation :one
SELECT ann_id, user_id, item_id, item_type, play_count, play_date, rating, rated_at, starred, starred_at FROM annotation
WHERE user_id = $1 AND item_id = $2 AND item_type = $3 LIMIT 1
`

type GetAnnotationParams struct {
	UserID   string `json:"user_id"`
	ItemID   string `json:"item_id"`
	ItemType string `json:"item_type"`
}

func (q *Queries) GetAnnotation(ctx context.Context, arg GetAnnotationParams) (Annotation, error) {
	row := q.db.QueryRow(ctx, getAnnotation, arg.UserID, arg.ItemID, arg.ItemType)
	var i Annotation
	err := row.Scan(
		&i.AnnID,
		&i.UserID,
		&i.ItemID,
		&i.ItemType,
		&i.PlayCount,
		&i.PlayDate,
		&i.Rating,
		&i.RatedAt,
		&i.Starred,
		&i.StarredAt,
	)
	return i, err
}

const incPlayCount = `-- name: IncPlayCount :exec
INSERT INTO annotation (
    ann_id, user_id, item_id, item_type, play_count, play_date
) VALUES (
    $1, $2, $3, $4, 1, $5
)
ON CONFLICT (user_id, item_id, item_type) DO UPDATE SET
    play_count = COALESCE(annotation.play_count, 0) + 1,
    play_date = EXCLUDED.play_date
`

type IncPlayCountParams struct {
	AnnID    string             `json:"ann_id"`
	UserID   string             `json:"user_id"`
	ItemID   string             `json:"item_id"`
	ItemType string             `json:"item_type"`
	PlayDate pgtype.Timestamptz `json:"play_date"`
}

func (q *Queries) IncPlayCount(ctx context.Context, arg IncPlayCountParams) error {
	_, err := q.db.Exec(ctx, incPlayCount,
		arg.AnnID,
		arg.UserID,
		arg.ItemID,
		arg.ItemType,
		arg.PlayDate,
	)
	return err
}

const setRating = `-- name: SetRating :exec
INSERT INTO annotation (
    ann_id, user_id, item_id, item_type, rating, rated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id, item_id, item_type) DO UPDATE SET
    rating = EXCLUDED.rating,
    rated_at = EXCLUDED.rated_at
`

type SetRatingParams struct {
	AnnID    string             `json:"ann_id"`
	UserID   string             `json:"user_id"`
	ItemID   string             `json:"item_id"`
	ItemType string             `json:"item_type"`
	Rating   *int32             `json:"rating"`
	RatedAt  pgtype.Timestamptz `json:"rated_at"`
}

func (q *Queries) SetRating(ctx context.Context, arg SetRatingParams) error {
	_, err := q.db.Exec(ctx, setRating,
		arg.AnnID,
		arg.UserID,
		arg.ItemID,
		arg.ItemType,
		arg.Rating,
		arg.RatedAt,
	)
	return err
}

const setStar = `-- name: SetStar :exec
INSERT INTO annotation (
    ann_id, user_id, item_id, item_type, starred, starred_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (user_id, item_id, item_type) DO UPDATE SET
    starred = EXCLUDED.starred,
    starred_at = EXCLUDED.starred_at
`

type SetStarParams struct {
	AnnID     string             `json:"ann_id"`
	UserID    string             `json:"user_id"`
	ItemID    string             `json:"item_id"`
	ItemType  string             `json:"item_type"`
	Starred   bool               `json:"starred"`
	StarredAt pgtype.Timestamptz `json:"starred_at"`
}

func (q *Queries) SetStar(ctx context.Context, arg SetStarParams) error {
	_, err := q.db.Exec(ctx, setStar,
		arg.AnnID,
		arg.UserID,
		arg.ItemID,
		arg.ItemType,
		arg.Starred,
		arg.StarredAt,
	)
	return err
}
