// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artist.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addLibraryArtist = `-- name: AddLibraryArtist :exec
INSERT INTO library_artist (library_id, artist_id, stats)
VALUES ($1, $2, $3)
ON CONFLICT (library_id, artist_id) DO UPDATE SET
    stats = EXCLUDED.stats
`

type AddLibraryArtistParams struct {
	LibraryID int32  `json:"library_id"`
	ArtistID  string `json:"artist_id"`
	Stats     string `json:"stats"`
}

func (q *Queries) AddLibraryArtist(ctx context.Context, arg AddLibraryArtistParams) error {
	_, err := q.db.Exec(ctx, addLibraryArtist, arg.LibraryID, arg.ArtistID, arg.Stats)
	return err
}

const countArtists = `-- name: CountArtists :one
SELECT count(*) FROM artist
WHERE missing = FALSE
`

func (q *Queries) CountArtists(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArtists)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteArtist = `-- name: DeleteArtist :exec
DELETE FROM artist
WHERE id = $1
`

func (q *Queries) DeleteArtist(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteArtist, id)
	return err
}

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, name, sort_artist_name, order_artist_name, mbz_artist_id, biography, small_image_url, medium_image_url, large_image_url, external_url, similar_artists, external_info_updated_at, missing, uploaded_image, created_at, updated_at FROM artist
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArtistByID(ctx context.Context, id string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByID, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortArtistName,
		&i.OrderArtistName,
		&i.MbzArtistID,
		&i.Biography,
		&i.SmallImageUrl,
		&i.MediumImageUrl,
		&i.LargeImageUrl,
		&i.ExternalUrl,
		&i.SimilarArtists,
		&i.ExternalInfoUpdatedAt,
		&i.Missing,
		&i.UploadedImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listArtists = `-- name: ListArtists :many
SELECT id, name, sort_artist_name, order_artist_name, mbz_artist_id, biography, small_image_url, medium_image_url, large_image_url, external_url, similar_artists, external_info_updated_at, missing, uploaded_image, created_at, updated_at FROM artist
WHERE missing = FALSE
ORDER BY sort_artist_name ASC, name ASC
LIMIT $1 OFFSET $2
`

type ListArtistsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArtists(ctx context.Context, arg ListArtistsParams) ([]Artist, error) {
	rows, err := q.db.Query(ctx, listArtists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortArtistName,
			&i.OrderArtistName,
			&i.MbzArtistID,
			&i.Biography,
			&i.SmallImageUrl,
			&i.MediumImageUrl,
			&i.LargeImageUrl,
			&i.ExternalUrl,
			&i.SimilarArtists,
			&i.ExternalInfoUpdatedAt,
			&i.Missing,
			&i.UploadedImage,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArtist = `-- name: UpsertArtist :one
INSERT INTO artist (
    id, name, sort_artist_name, order_artist_name, mbz_artist_id,
    biography, small_image_url, medium_image_url, large_image_url,
    external_url, similar_artists, external_info_updated_at, missing,
    uploaded_image, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14, $15, $16
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    sort_artist_name = EXCLUDED.sort_artist_name,
    order_artist_name = EXCLUDED.order_artist_name,
    mbz_artist_id = EXCLUDED.mbz_artist_id,
    biography = EXCLUDED.biography,
    small_image_url = EXCLUDED.small_image_url,
    medium_image_url = EXCLUDED.medium_image_url,
    large_image_url = EXCLUDED.large_image_url,
    external_url = EXCLUDED.external_url,
    similar_artists = EXCLUDED.similar_artists,
    external_info_updated_at = EXCLUDED.external_info_updated_at,
    missing = EXCLUDED.missing,
    uploaded_image = EXCLUDED.uploaded_image,
    updated_at = EXCLUDED.updated_at
RETURNING id, name, sort_artist_name, order_artist_name, mbz_artist_id, biography, small_image_url, medium_image_url, large_image_url, external_url, similar_artists, external_info_updated_at, missing, uploaded_image, created_at, updated_at
`

type UpsertArtistParams struct {
	ID                    string             `json:"id"`
	Name                  string             `json:"name"`
	SortArtistName        string             `json:"sort_artist_name"`
	OrderArtistName       string             `json:"order_artist_name"`
	MbzArtistID           string             `json:"mbz_artist_id"`
	Biography             string             `json:"biography"`
	SmallImageUrl         string             `json:"small_image_url"`
	MediumImageUrl        string             `json:"medium_image_url"`
	LargeImageUrl         string             `json:"large_image_url"`
	ExternalUrl           string             `json:"external_url"`
	SimilarArtists        string             `json:"similar_artists"`
	ExternalInfoUpdatedAt pgtype.Timestamptz `json:"external_info_updated_at"`
	Missing               bool               `json:"missing"`
	UploadedImage         string             `json:"uploaded_image"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertArtist(ctx context.Context, arg UpsertArtistParams) (Artist, error) {
	row := q.db.QueryRow(ctx, upsertArtist,
		arg.ID,
		arg.Name,
		arg.SortArtistName,
		arg.OrderArtistName,
		arg.MbzArtistID,
		arg.Biography,
		arg.SmallImageUrl,
		arg.MediumImageUrl,
		arg.LargeImageUrl,
		arg.ExternalUrl,
		arg.SimilarArtists,
		arg.ExternalInfoUpdatedAt,
		arg.Missing,
		arg.UploadedImage,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SortArtistName,
		&i.OrderArtistName,
		&i.MbzArtistID,
		&i.Biography,
		&i.SmallImageUrl,
		&i.MediumImageUrl,
		&i.LargeImageUrl,
		&i.ExternalUrl,
		&i.SimilarArtists,
		&i.ExternalInfoUpdatedAt,
		&i.Missing,
		&i.UploadedImage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
