// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLibraries = `-- name: CountLibraries :one
SELECT count(*) FROM library
`

func (q *Queries) CountLibraries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLibraries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLibrary = `-- name: DeleteLibrary :exec
DELETE FROM library
WHERE id = $1
`

func (q *Queries) DeleteLibrary(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteLibrary, id)
	return err
}

const getLibraryByID = `-- name: GetLibraryByID :one
SELECT id, name, path, remote_path, last_scan_at, last_scan_started_at, full_scan_in_progress, total_songs, total_albums, total_artists, total_folders, total_files, total_missing_files, total_size, total_duration, default_new_users, created_at, updated_at FROM library
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLibraryByID(ctx context.Context, id int32) (Library, error) {
	row := q.db.QueryRow(ctx, getLibraryByID, id)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.RemotePath,
		&i.LastScanAt,
		&i.LastScanStartedAt,
		&i.FullScanInProgress,
		&i.TotalSongs,
		&i.TotalAlbums,
		&i.TotalArtists,
		&i.TotalFolders,
		&i.TotalFiles,
		&i.TotalMissingFiles,
		&i.TotalSize,
		&i.TotalDuration,
		&i.DefaultNewUsers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLibraryPath = `-- name: GetLibraryPath :one
SELECT path FROM library
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLibraryPath(ctx context.Context, id int32) (string, error) {
	row := q.db.QueryRow(ctx, getLibraryPath, id)
	var path string
	err := row.Scan(&path)
	return path, err
}

const getUsersWithLibraryAccess = `-- name: GetUsersWithLibraryAccess :many
SELECT u.id, u.user_name, u.name, u.email, u.password, u.is_admin, u.token_epoch, u.scrobble_filter, u.last_login_at, u.last_access_at, u.created_at, u.updated_at FROM "user" u
JOIN user_library ul ON u.id = ul.user_id
WHERE ul.library_id = $1
UNION
SELECT id, user_name, name, email, password, is_admin, token_epoch, scrobble_filter, last_login_at, last_access_at, created_at, updated_at FROM "user" WHERE is_admin = TRUE
ORDER BY user_name ASC
`

func (q *Queries) GetUsersWithLibraryAccess(ctx context.Context, libraryID int32) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersWithLibraryAccess, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.IsAdmin,
			&i.TokenEpoch,
			&i.ScrobbleFilter,
			&i.LastLoginAt,
			&i.LastAccessAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraries = `-- name: ListLibraries :many
SELECT id, name, path, remote_path, last_scan_at, last_scan_started_at, full_scan_in_progress, total_songs, total_albums, total_artists, total_folders, total_files, total_missing_files, total_size, total_duration, default_new_users, created_at, updated_at FROM library
ORDER BY name ASC
`

func (q *Queries) ListLibraries(ctx context.Context) ([]Library, error) {
	rows, err := q.db.Query(ctx, listLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.RemotePath,
			&i.LastScanAt,
			&i.LastScanStartedAt,
			&i.FullScanInProgress,
			&i.TotalSongs,
			&i.TotalAlbums,
			&i.TotalArtists,
			&i.TotalFolders,
			&i.TotalFiles,
			&i.TotalMissingFiles,
			&i.TotalSize,
			&i.TotalDuration,
			&i.DefaultNewUsers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshLibraryStats = `-- name: RefreshLibraryStats :exec
UPDATE library l SET
    total_songs = COALESCE((SELECT count(*) FROM media_file WHERE library_id = l.id AND missing = FALSE), 0),
    total_albums = COALESCE((SELECT count(*) FROM album WHERE library_id = l.id AND missing = FALSE), 0),
    total_artists = COALESCE((SELECT count(DISTINCT mfa.artist_id) FROM media_file_artists mfa JOIN media_file mf ON mfa.media_file_id = mf.id WHERE mf.library_id = l.id AND mf.missing = FALSE), 0),
    total_folders = COALESCE((SELECT count(*) FROM folder WHERE library_id = l.id AND missing = FALSE), 0),
    total_files = COALESCE((SELECT count(*) FROM media_file WHERE library_id = l.id), 0),
    total_missing_files = COALESCE((SELECT count(*) FROM media_file WHERE library_id = l.id AND missing = TRUE), 0),
    total_size = COALESCE((SELECT sum(size) FROM media_file WHERE library_id = l.id AND missing = FALSE), 0),
    total_duration = COALESCE((SELECT sum(duration) FROM media_file WHERE library_id = l.id AND missing = FALSE), 0),
    updated_at = CURRENT_TIMESTAMP
WHERE l.id = $1
`

func (q *Queries) RefreshLibraryStats(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, refreshLibraryStats, id)
	return err
}

const scanBegin = `-- name: ScanBegin :exec
UPDATE library
SET full_scan_in_progress = $2, last_scan_started_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type ScanBeginParams struct {
	ID                 int32 `json:"id"`
	FullScanInProgress bool  `json:"full_scan_in_progress"`
}

func (q *Queries) ScanBegin(ctx context.Context, arg ScanBeginParams) error {
	_, err := q.db.Exec(ctx, scanBegin, arg.ID, arg.FullScanInProgress)
	return err
}

const scanEnd = `-- name: ScanEnd :exec
UPDATE library
SET full_scan_in_progress = FALSE, last_scan_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ScanEnd(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, scanEnd, id)
	return err
}

const scanInProgress = `-- name: ScanInProgress :one
SELECT EXISTS (
    SELECT 1 FROM library WHERE full_scan_in_progress = TRUE
) AS in_progress
`

func (q *Queries) ScanInProgress(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, scanInProgress)
	var in_progress bool
	err := row.Scan(&in_progress)
	return in_progress, err
}

const upsertLibrary = `-- name: UpsertLibrary :one
INSERT INTO library (
    id, name, path, remote_path, default_new_users, created_at, updated_at
) VALUES (
    CASE WHEN $1::int > 0 THEN $1::int ELSE nextval('library_id_seq') END,
    $2::varchar,
    $3::text,
    $4::text,
    $5::boolean,
    $6::timestamptz,
    $7::timestamptz
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    path = EXCLUDED.path,
    remote_path = EXCLUDED.remote_path,
    default_new_users = EXCLUDED.default_new_users,
    updated_at = EXCLUDED.updated_at
RETURNING id, name, path, remote_path, last_scan_at, last_scan_started_at, full_scan_in_progress, total_songs, total_albums, total_artists, total_folders, total_files, total_missing_files, total_size, total_duration, default_new_users, created_at, updated_at
`

type UpsertLibraryParams struct {
	ID              int32              `json:"id"`
	Name            string             `json:"name"`
	Path            string             `json:"path"`
	RemotePath      string             `json:"remote_path"`
	DefaultNewUsers bool               `json:"default_new_users"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertLibrary(ctx context.Context, arg UpsertLibraryParams) (Library, error) {
	row := q.db.QueryRow(ctx, upsertLibrary,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.RemotePath,
		arg.DefaultNewUsers,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Library
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.RemotePath,
		&i.LastScanAt,
		&i.LastScanStartedAt,
		&i.FullScanInProgress,
		&i.TotalSongs,
		&i.TotalAlbums,
		&i.TotalArtists,
		&i.TotalFolders,
		&i.TotalFiles,
		&i.TotalMissingFiles,
		&i.TotalSize,
		&i.TotalDuration,
		&i.DefaultNewUsers,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
