// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media_file.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMediaFileArtist = `-- name: AddMediaFileArtist :exec
INSERT INTO media_file_artists (media_file_id, artist_id, role, sub_role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (artist_id, media_file_id, role, sub_role) DO NOTHING
`

type AddMediaFileArtistParams struct {
	MediaFileID string `json:"media_file_id"`
	ArtistID    string `json:"artist_id"`
	Role        string `json:"role"`
	SubRole     string `json:"sub_role"`
}

func (q *Queries) AddMediaFileArtist(ctx context.Context, arg AddMediaFileArtistParams) error {
	_, err := q.db.Exec(ctx, addMediaFileArtist,
		arg.MediaFileID,
		arg.ArtistID,
		arg.Role,
		arg.SubRole,
	)
	return err
}

const countMediaFiles = `-- name: CountMediaFiles :one
SELECT count(*) FROM media_file
WHERE missing = FALSE
`

func (q *Queries) CountMediaFiles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMediaFiles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMediaFile = `-- name: DeleteMediaFile :exec
DELETE FROM media_file
WHERE id = $1
`

func (q *Queries) DeleteMediaFile(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteMediaFile, id)
	return err
}

const getMediaFileByID = `-- name: GetMediaFileByID :one
SELECT id, pid, library_id, folder_id, path, title, album, artist, artist_id, album_artist, album_artist_id, album_id, has_cover_art, track_number, disc_number, disc_subtitle, year, date, original_year, original_date, release_year, release_date, size, suffix, duration, bit_rate, sample_rate, bit_depth, channels, codec, probe_data, genre, sort_title, sort_album_name, sort_artist_name, sort_album_artist_name, order_title, order_album_name, order_artist_name, order_album_artist_name, compilation, comment, lyrics, bpm, explicit_status, catalog_num, mbz_recording_id, mbz_release_track_id, mbz_album_id, mbz_release_group_id, mbz_artist_id, mbz_album_artist_id, mbz_album_type, mbz_album_comment, rg_album_gain, rg_album_peak, rg_track_gain, rg_track_peak, tags, participants, missing, birth_time, created_at, updated_at FROM media_file
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMediaFileByID(ctx context.Context, id string) (MediaFile, error) {
	row := q.db.QueryRow(ctx, getMediaFileByID, id)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.LibraryID,
		&i.FolderID,
		&i.Path,
		&i.Title,
		&i.Album,
		&i.Artist,
		&i.ArtistID,
		&i.AlbumArtist,
		&i.AlbumArtistID,
		&i.AlbumID,
		&i.HasCoverArt,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DiscSubtitle,
		&i.Year,
		&i.Date,
		&i.OriginalYear,
		&i.OriginalDate,
		&i.ReleaseYear,
		&i.ReleaseDate,
		&i.Size,
		&i.Suffix,
		&i.Duration,
		&i.BitRate,
		&i.SampleRate,
		&i.BitDepth,
		&i.Channels,
		&i.Codec,
		&i.ProbeData,
		&i.Genre,
		&i.SortTitle,
		&i.SortAlbumName,
		&i.SortArtistName,
		&i.SortAlbumArtistName,
		&i.OrderTitle,
		&i.OrderAlbumName,
		&i.OrderArtistName,
		&i.OrderAlbumArtistName,
		&i.Compilation,
		&i.Comment,
		&i.Lyrics,
		&i.Bpm,
		&i.ExplicitStatus,
		&i.CatalogNum,
		&i.MbzRecordingID,
		&i.MbzReleaseTrackID,
		&i.MbzAlbumID,
		&i.MbzReleaseGroupID,
		&i.MbzArtistID,
		&i.MbzAlbumArtistID,
		&i.MbzAlbumType,
		&i.MbzAlbumComment,
		&i.RgAlbumGain,
		&i.RgAlbumPeak,
		&i.RgTrackGain,
		&i.RgTrackPeak,
		&i.Tags,
		&i.Participants,
		&i.Missing,
		&i.BirthTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMediaFileByPath = `-- name: GetMediaFileByPath :one
SELECT id, pid, library_id, folder_id, path, title, album, artist, artist_id, album_artist, album_artist_id, album_id, has_cover_art, track_number, disc_number, disc_subtitle, year, date, original_year, original_date, release_year, release_date, size, suffix, duration, bit_rate, sample_rate, bit_depth, channels, codec, probe_data, genre, sort_title, sort_album_name, sort_artist_name, sort_album_artist_name, order_title, order_album_name, order_artist_name, order_album_artist_name, compilation, comment, lyrics, bpm, explicit_status, catalog_num, mbz_recording_id, mbz_release_track_id, mbz_album_id, mbz_release_group_id, mbz_artist_id, mbz_album_artist_id, mbz_album_type, mbz_album_comment, rg_album_gain, rg_album_peak, rg_track_gain, rg_track_peak, tags, participants, missing, birth_time, created_at, updated_at FROM media_file
WHERE path = $1 LIMIT 1
`

func (q *Queries) GetMediaFileByPath(ctx context.Context, path string) (MediaFile, error) {
	row := q.db.QueryRow(ctx, getMediaFileByPath, path)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.LibraryID,
		&i.FolderID,
		&i.Path,
		&i.Title,
		&i.Album,
		&i.Artist,
		&i.ArtistID,
		&i.AlbumArtist,
		&i.AlbumArtistID,
		&i.AlbumID,
		&i.HasCoverArt,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DiscSubtitle,
		&i.Year,
		&i.Date,
		&i.OriginalYear,
		&i.OriginalDate,
		&i.ReleaseYear,
		&i.ReleaseDate,
		&i.Size,
		&i.Suffix,
		&i.Duration,
		&i.BitRate,
		&i.SampleRate,
		&i.BitDepth,
		&i.Channels,
		&i.Codec,
		&i.ProbeData,
		&i.Genre,
		&i.SortTitle,
		&i.SortAlbumName,
		&i.SortArtistName,
		&i.SortAlbumArtistName,
		&i.OrderTitle,
		&i.OrderAlbumName,
		&i.OrderArtistName,
		&i.OrderAlbumArtistName,
		&i.Compilation,
		&i.Comment,
		&i.Lyrics,
		&i.Bpm,
		&i.ExplicitStatus,
		&i.CatalogNum,
		&i.MbzRecordingID,
		&i.MbzReleaseTrackID,
		&i.MbzAlbumID,
		&i.MbzReleaseGroupID,
		&i.MbzArtistID,
		&i.MbzAlbumArtistID,
		&i.MbzAlbumType,
		&i.MbzAlbumComment,
		&i.RgAlbumGain,
		&i.RgAlbumPeak,
		&i.RgTrackGain,
		&i.RgTrackPeak,
		&i.Tags,
		&i.Participants,
		&i.Missing,
		&i.BirthTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMediaFilesByAlbum = `-- name: ListMediaFilesByAlbum :many
SELECT id, pid, library_id, folder_id, path, title, album, artist, artist_id, album_artist, album_artist_id, album_id, has_cover_art, track_number, disc_number, disc_subtitle, year, date, original_year, original_date, release_year, release_date, size, suffix, duration, bit_rate, sample_rate, bit_depth, channels, codec, probe_data, genre, sort_title, sort_album_name, sort_artist_name, sort_album_artist_name, order_title, order_album_name, order_artist_name, order_album_artist_name, compilation, comment, lyrics, bpm, explicit_status, catalog_num, mbz_recording_id, mbz_release_track_id, mbz_album_id, mbz_release_group_id, mbz_artist_id, mbz_album_artist_id, mbz_album_type, mbz_album_comment, rg_album_gain, rg_album_peak, rg_track_gain, rg_track_peak, tags, participants, missing, birth_time, created_at, updated_at FROM media_file
WHERE album_id = $1 AND missing = FALSE
ORDER BY disc_number ASC, track_number ASC
`

func (q *Queries) ListMediaFilesByAlbum(ctx context.Context, albumID string) ([]MediaFile, error) {
	rows, err := q.db.Query(ctx, listMediaFilesByAlbum, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.LibraryID,
			&i.FolderID,
			&i.Path,
			&i.Title,
			&i.Album,
			&i.Artist,
			&i.ArtistID,
			&i.AlbumArtist,
			&i.AlbumArtistID,
			&i.AlbumID,
			&i.HasCoverArt,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DiscSubtitle,
			&i.Year,
			&i.Date,
			&i.OriginalYear,
			&i.OriginalDate,
			&i.ReleaseYear,
			&i.ReleaseDate,
			&i.Size,
			&i.Suffix,
			&i.Duration,
			&i.BitRate,
			&i.SampleRate,
			&i.BitDepth,
			&i.Channels,
			&i.Codec,
			&i.ProbeData,
			&i.Genre,
			&i.SortTitle,
			&i.SortAlbumName,
			&i.SortArtistName,
			&i.SortAlbumArtistName,
			&i.OrderTitle,
			&i.OrderAlbumName,
			&i.OrderArtistName,
			&i.OrderAlbumArtistName,
			&i.Compilation,
			&i.Comment,
			&i.Lyrics,
			&i.Bpm,
			&i.ExplicitStatus,
			&i.CatalogNum,
			&i.MbzRecordingID,
			&i.MbzReleaseTrackID,
			&i.MbzAlbumID,
			&i.MbzReleaseGroupID,
			&i.MbzArtistID,
			&i.MbzAlbumArtistID,
			&i.MbzAlbumType,
			&i.MbzAlbumComment,
			&i.RgAlbumGain,
			&i.RgAlbumPeak,
			&i.RgTrackGain,
			&i.RgTrackPeak,
			&i.Tags,
			&i.Participants,
			&i.Missing,
			&i.BirthTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaFilesByArtist = `-- name: ListMediaFilesByArtist :many
SELECT id, pid, library_id, folder_id, path, title, album, artist, artist_id, album_artist, album_artist_id, album_id, has_cover_art, track_number, disc_number, disc_subtitle, year, date, original_year, original_date, release_year, release_date, size, suffix, duration, bit_rate, sample_rate, bit_depth, channels, codec, probe_data, genre, sort_title, sort_album_name, sort_artist_name, sort_album_artist_name, order_title, order_album_name, order_artist_name, order_album_artist_name, compilation, comment, lyrics, bpm, explicit_status, catalog_num, mbz_recording_id, mbz_release_track_id, mbz_album_id, mbz_release_group_id, mbz_artist_id, mbz_album_artist_id, mbz_album_type, mbz_album_comment, rg_album_gain, rg_album_peak, rg_track_gain, rg_track_peak, tags, participants, missing, birth_time, created_at, updated_at FROM media_file
WHERE (artist_id = $1 OR album_artist_id = $1) AND missing = FALSE
ORDER BY year DESC, album ASC, disc_number ASC, track_number ASC
`

func (q *Queries) ListMediaFilesByArtist(ctx context.Context, artistID string) ([]MediaFile, error) {
	rows, err := q.db.Query(ctx, listMediaFilesByArtist, artistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.LibraryID,
			&i.FolderID,
			&i.Path,
			&i.Title,
			&i.Album,
			&i.Artist,
			&i.ArtistID,
			&i.AlbumArtist,
			&i.AlbumArtistID,
			&i.AlbumID,
			&i.HasCoverArt,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DiscSubtitle,
			&i.Year,
			&i.Date,
			&i.OriginalYear,
			&i.OriginalDate,
			&i.ReleaseYear,
			&i.ReleaseDate,
			&i.Size,
			&i.Suffix,
			&i.Duration,
			&i.BitRate,
			&i.SampleRate,
			&i.BitDepth,
			&i.Channels,
			&i.Codec,
			&i.ProbeData,
			&i.Genre,
			&i.SortTitle,
			&i.SortAlbumName,
			&i.SortArtistName,
			&i.SortAlbumArtistName,
			&i.OrderTitle,
			&i.OrderAlbumName,
			&i.OrderArtistName,
			&i.OrderAlbumArtistName,
			&i.Compilation,
			&i.Comment,
			&i.Lyrics,
			&i.Bpm,
			&i.ExplicitStatus,
			&i.CatalogNum,
			&i.MbzRecordingID,
			&i.MbzReleaseTrackID,
			&i.MbzAlbumID,
			&i.MbzReleaseGroupID,
			&i.MbzArtistID,
			&i.MbzAlbumArtistID,
			&i.MbzAlbumType,
			&i.MbzAlbumComment,
			&i.RgAlbumGain,
			&i.RgAlbumPeak,
			&i.RgTrackGain,
			&i.RgTrackPeak,
			&i.Tags,
			&i.Participants,
			&i.Missing,
			&i.BirthTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMediaFiles = `-- name: SearchMediaFiles :many
SELECT id, pid, library_id, folder_id, path, title, album, artist, artist_id, album_artist, album_artist_id, album_id, has_cover_art, track_number, disc_number, disc_subtitle, year, date, original_year, original_date, release_year, release_date, size, suffix, duration, bit_rate, sample_rate, bit_depth, channels, codec, probe_data, genre, sort_title, sort_album_name, sort_artist_name, sort_album_artist_name, order_title, order_album_name, order_artist_name, order_album_artist_name, compilation, comment, lyrics, bpm, explicit_status, catalog_num, mbz_recording_id, mbz_release_track_id, mbz_album_id, mbz_release_group_id, mbz_artist_id, mbz_album_artist_id, mbz_album_type, mbz_album_comment, rg_album_gain, rg_album_peak, rg_track_gain, rg_track_peak, tags, participants, missing, birth_time, created_at, updated_at FROM media_file
WHERE missing = FALSE
  AND (title ILIKE '%' || $1 || '%' OR artist ILIKE '%' || $1 || '%' OR album ILIKE '%' || $1 || '%')
ORDER BY title ASC
LIMIT $2 OFFSET $3
`

type SearchMediaFilesParams struct {
	Column1 *string `json:"column_1"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

func (q *Queries) SearchMediaFiles(ctx context.Context, arg SearchMediaFilesParams) ([]MediaFile, error) {
	rows, err := q.db.Query(ctx, searchMediaFiles, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.LibraryID,
			&i.FolderID,
			&i.Path,
			&i.Title,
			&i.Album,
			&i.Artist,
			&i.ArtistID,
			&i.AlbumArtist,
			&i.AlbumArtistID,
			&i.AlbumID,
			&i.HasCoverArt,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DiscSubtitle,
			&i.Year,
			&i.Date,
			&i.OriginalYear,
			&i.OriginalDate,
			&i.ReleaseYear,
			&i.ReleaseDate,
			&i.Size,
			&i.Suffix,
			&i.Duration,
			&i.BitRate,
			&i.SampleRate,
			&i.BitDepth,
			&i.Channels,
			&i.Codec,
			&i.ProbeData,
			&i.Genre,
			&i.SortTitle,
			&i.SortAlbumName,
			&i.SortArtistName,
			&i.SortAlbumArtistName,
			&i.OrderTitle,
			&i.OrderAlbumName,
			&i.OrderArtistName,
			&i.OrderAlbumArtistName,
			&i.Compilation,
			&i.Comment,
			&i.Lyrics,
			&i.Bpm,
			&i.ExplicitStatus,
			&i.CatalogNum,
			&i.MbzRecordingID,
			&i.MbzReleaseTrackID,
			&i.MbzAlbumID,
			&i.MbzReleaseGroupID,
			&i.MbzArtistID,
			&i.MbzAlbumArtistID,
			&i.MbzAlbumType,
			&i.MbzAlbumComment,
			&i.RgAlbumGain,
			&i.RgAlbumPeak,
			&i.RgTrackGain,
			&i.RgTrackPeak,
			&i.Tags,
			&i.Participants,
			&i.Missing,
			&i.BirthTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMediaFile = `-- name: UpsertMediaFile :one
INSERT INTO media_file (
    id, pid, library_id, folder_id, path, title, album, artist, artist_id,
    album_artist, album_artist_id, album_id, has_cover_art, track_number, disc_number,
    disc_subtitle, year, date, original_year, original_date, release_year, release_date,
    size, suffix, duration, bit_rate, sample_rate, bit_depth, channels, codec,
    probe_data, genre, sort_title, sort_album_name, sort_artist_name, sort_album_artist_name,
    order_title, order_album_name, order_artist_name, order_album_artist_name,
    compilation, comment, lyrics, bpm, explicit_status, catalog_num,
    mbz_recording_id, mbz_release_track_id, mbz_album_id, mbz_release_group_id,
    mbz_artist_id, mbz_album_artist_id, mbz_album_type, mbz_album_comment,
    rg_album_gain, rg_album_peak, rg_track_gain, rg_track_peak,
    tags, participants, missing, birth_time, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21, $22,
    $23, $24, $25, $26, $27, $28, $29, $30,
    $31, $32, $33, $34, $35, $36,
    $37, $38, $39, $40,
    $41, $42, $43, $44, $45, $46,
    $47, $48, $49, $50,
    $51, $52, $53, $54,
    $55, $56, $57, $58,
    $59, $60, $61, $62, $63, $64
)
ON CONFLICT (id) DO UPDATE SET
    pid = EXCLUDED.pid,
    library_id = EXCLUDED.library_id,
    folder_id = EXCLUDED.folder_id,
    path = EXCLUDED.path,
    title = EXCLUDED.title,
    album = EXCLUDED.album,
    artist = EXCLUDED.artist,
    artist_id = EXCLUDED.artist_id,
    album_artist = EXCLUDED.album_artist,
    album_artist_id = EXCLUDED.album_artist_id,
    album_id = EXCLUDED.album_id,
    has_cover_art = EXCLUDED.has_cover_art,
    track_number = EXCLUDED.track_number,
    disc_number = EXCLUDED.disc_number,
    disc_subtitle = EXCLUDED.disc_subtitle,
    year = EXCLUDED.year,
    date = EXCLUDED.date,
    original_year = EXCLUDED.original_year,
    original_date = EXCLUDED.original_date,
    release_year = EXCLUDED.release_year,
    release_date = EXCLUDED.release_date,
    size = EXCLUDED.size,
    suffix = EXCLUDED.suffix,
    duration = EXCLUDED.duration,
    bit_rate = EXCLUDED.bit_rate,
    sample_rate = EXCLUDED.sample_rate,
    bit_depth = EXCLUDED.bit_depth,
    channels = EXCLUDED.channels,
    codec = EXCLUDED.codec,
    probe_data = EXCLUDED.probe_data,
    genre = EXCLUDED.genre,
    sort_title = EXCLUDED.sort_title,
    sort_album_name = EXCLUDED.sort_album_name,
    sort_artist_name = EXCLUDED.sort_artist_name,
    sort_album_artist_name = EXCLUDED.sort_album_artist_name,
    order_title = EXCLUDED.order_title,
    order_album_name = EXCLUDED.order_album_name,
    order_artist_name = EXCLUDED.order_artist_name,
    order_album_artist_name = EXCLUDED.order_album_artist_name,
    compilation = EXCLUDED.compilation,
    comment = EXCLUDED.comment,
    lyrics = EXCLUDED.lyrics,
    bpm = EXCLUDED.bpm,
    explicit_status = EXCLUDED.explicit_status,
    catalog_num = EXCLUDED.catalog_num,
    mbz_recording_id = EXCLUDED.mbz_recording_id,
    mbz_release_track_id = EXCLUDED.mbz_release_track_id,
    mbz_album_id = EXCLUDED.mbz_album_id,
    mbz_release_group_id = EXCLUDED.mbz_release_group_id,
    mbz_artist_id = EXCLUDED.mbz_artist_id,
    mbz_album_artist_id = EXCLUDED.mbz_album_artist_id,
    mbz_album_type = EXCLUDED.mbz_album_type,
    mbz_album_comment = EXCLUDED.mbz_album_comment,
    rg_album_gain = EXCLUDED.rg_album_gain,
    rg_album_peak = EXCLUDED.rg_album_peak,
    rg_track_gain = EXCLUDED.rg_track_gain,
    rg_track_peak = EXCLUDED.rg_track_peak,
    tags = EXCLUDED.tags,
    participants = EXCLUDED.participants,
    missing = EXCLUDED.missing,
    birth_time = EXCLUDED.birth_time,
    updated_at = EXCLUDED.updated_at
RETURNING id, pid, library_id, folder_id, path, title, album, artist, artist_id, album_artist, album_artist_id, album_id, has_cover_art, track_number, disc_number, disc_subtitle, year, date, original_year, original_date, release_year, release_date, size, suffix, duration, bit_rate, sample_rate, bit_depth, channels, codec, probe_data, genre, sort_title, sort_album_name, sort_artist_name, sort_album_artist_name, order_title, order_album_name, order_artist_name, order_album_artist_name, compilation, comment, lyrics, bpm, explicit_status, catalog_num, mbz_recording_id, mbz_release_track_id, mbz_album_id, mbz_release_group_id, mbz_artist_id, mbz_album_artist_id, mbz_album_type, mbz_album_comment, rg_album_gain, rg_album_peak, rg_track_gain, rg_track_peak, tags, participants, missing, birth_time, created_at, updated_at
`

type UpsertMediaFileParams struct {
	ID                   string             `json:"id"`
	Pid                  string             `json:"pid"`
	LibraryID            int32              `json:"library_id"`
	FolderID             string             `json:"folder_id"`
	Path                 string             `json:"path"`
	Title                string             `json:"title"`
	Album                string             `json:"album"`
	Artist               string             `json:"artist"`
	ArtistID             string             `json:"artist_id"`
	AlbumArtist          string             `json:"album_artist"`
	AlbumArtistID        string             `json:"album_artist_id"`
	AlbumID              string             `json:"album_id"`
	HasCoverArt          bool               `json:"has_cover_art"`
	TrackNumber          int32              `json:"track_number"`
	DiscNumber           int32              `json:"disc_number"`
	DiscSubtitle         string             `json:"disc_subtitle"`
	Year                 int32              `json:"year"`
	Date                 string             `json:"date"`
	OriginalYear         int32              `json:"original_year"`
	OriginalDate         string             `json:"original_date"`
	ReleaseYear          int32              `json:"release_year"`
	ReleaseDate          string             `json:"release_date"`
	Size                 int64              `json:"size"`
	Suffix               string             `json:"suffix"`
	Duration             float32            `json:"duration"`
	BitRate              int32              `json:"bit_rate"`
	SampleRate           int32              `json:"sample_rate"`
	BitDepth             *int32             `json:"bit_depth"`
	Channels             int32              `json:"channels"`
	Codec                string             `json:"codec"`
	ProbeData            string             `json:"probe_data"`
	Genre                string             `json:"genre"`
	SortTitle            string             `json:"sort_title"`
	SortAlbumName        string             `json:"sort_album_name"`
	SortArtistName       string             `json:"sort_artist_name"`
	SortAlbumArtistName  string             `json:"sort_album_artist_name"`
	OrderTitle           string             `json:"order_title"`
	OrderAlbumName       string             `json:"order_album_name"`
	OrderArtistName      string             `json:"order_artist_name"`
	OrderAlbumArtistName string             `json:"order_album_artist_name"`
	Compilation          bool               `json:"compilation"`
	Comment              string             `json:"comment"`
	Lyrics               string             `json:"lyrics"`
	Bpm                  *int32             `json:"bpm"`
	ExplicitStatus       string             `json:"explicit_status"`
	CatalogNum           string             `json:"catalog_num"`
	MbzRecordingID       string             `json:"mbz_recording_id"`
	MbzReleaseTrackID    string             `json:"mbz_release_track_id"`
	MbzAlbumID           string             `json:"mbz_album_id"`
	MbzReleaseGroupID    string             `json:"mbz_release_group_id"`
	MbzArtistID          string             `json:"mbz_artist_id"`
	MbzAlbumArtistID     string             `json:"mbz_album_artist_id"`
	MbzAlbumType         string             `json:"mbz_album_type"`
	MbzAlbumComment      string             `json:"mbz_album_comment"`
	RgAlbumGain          *float64           `json:"rg_album_gain"`
	RgAlbumPeak          *float64           `json:"rg_album_peak"`
	RgTrackGain          *float64           `json:"rg_track_gain"`
	RgTrackPeak          *float64           `json:"rg_track_peak"`
	Tags                 string             `json:"tags"`
	Participants         string             `json:"participants"`
	Missing              bool               `json:"missing"`
	BirthTime            pgtype.Timestamptz `json:"birth_time"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertMediaFile(ctx context.Context, arg UpsertMediaFileParams) (MediaFile, error) {
	row := q.db.QueryRow(ctx, upsertMediaFile,
		arg.ID,
		arg.Pid,
		arg.LibraryID,
		arg.FolderID,
		arg.Path,
		arg.Title,
		arg.Album,
		arg.Artist,
		arg.ArtistID,
		arg.AlbumArtist,
		arg.AlbumArtistID,
		arg.AlbumID,
		arg.HasCoverArt,
		arg.TrackNumber,
		arg.DiscNumber,
		arg.DiscSubtitle,
		arg.Year,
		arg.Date,
		arg.OriginalYear,
		arg.OriginalDate,
		arg.ReleaseYear,
		arg.ReleaseDate,
		arg.Size,
		arg.Suffix,
		arg.Duration,
		arg.BitRate,
		arg.SampleRate,
		arg.BitDepth,
		arg.Channels,
		arg.Codec,
		arg.ProbeData,
		arg.Genre,
		arg.SortTitle,
		arg.SortAlbumName,
		arg.SortArtistName,
		arg.SortAlbumArtistName,
		arg.OrderTitle,
		arg.OrderAlbumName,
		arg.OrderArtistName,
		arg.OrderAlbumArtistName,
		arg.Compilation,
		arg.Comment,
		arg.Lyrics,
		arg.Bpm,
		arg.ExplicitStatus,
		arg.CatalogNum,
		arg.MbzRecordingID,
		arg.MbzReleaseTrackID,
		arg.MbzAlbumID,
		arg.MbzReleaseGroupID,
		arg.MbzArtistID,
		arg.MbzAlbumArtistID,
		arg.MbzAlbumType,
		arg.MbzAlbumComment,
		arg.RgAlbumGain,
		arg.RgAlbumPeak,
		arg.RgTrackGain,
		arg.RgTrackPeak,
		arg.Tags,
		arg.Participants,
		arg.Missing,
		arg.BirthTime,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i MediaFile
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.LibraryID,
		&i.FolderID,
		&i.Path,
		&i.Title,
		&i.Album,
		&i.Artist,
		&i.ArtistID,
		&i.AlbumArtist,
		&i.AlbumArtistID,
		&i.AlbumID,
		&i.HasCoverArt,
		&i.TrackNumber,
		&i.DiscNumber,
		&i.DiscSubtitle,
		&i.Year,
		&i.Date,
		&i.OriginalYear,
		&i.OriginalDate,
		&i.ReleaseYear,
		&i.ReleaseDate,
		&i.Size,
		&i.Suffix,
		&i.Duration,
		&i.BitRate,
		&i.SampleRate,
		&i.BitDepth,
		&i.Channels,
		&i.Codec,
		&i.ProbeData,
		&i.Genre,
		&i.SortTitle,
		&i.SortAlbumName,
		&i.SortArtistName,
		&i.SortAlbumArtistName,
		&i.OrderTitle,
		&i.OrderAlbumName,
		&i.OrderArtistName,
		&i.OrderAlbumArtistName,
		&i.Compilation,
		&i.Comment,
		&i.Lyrics,
		&i.Bpm,
		&i.ExplicitStatus,
		&i.CatalogNum,
		&i.MbzRecordingID,
		&i.MbzReleaseTrackID,
		&i.MbzAlbumID,
		&i.MbzReleaseGroupID,
		&i.MbzArtistID,
		&i.MbzAlbumArtistID,
		&i.MbzAlbumType,
		&i.MbzAlbumComment,
		&i.RgAlbumGain,
		&i.RgAlbumPeak,
		&i.RgTrackGain,
		&i.RgTrackPeak,
		&i.Tags,
		&i.Participants,
		&i.Missing,
		&i.BirthTime,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
