// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pgdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID                    string             `json:"id"`
	LibraryID             int32              `json:"library_id"`
	Name                  string             `json:"name"`
	ArtistID              string             `json:"artist_id"`
	Artist                string             `json:"artist"`
	AlbumArtist           string             `json:"album_artist"`
	AlbumArtistID         string             `json:"album_artist_id"`
	EmbedArtPath          string             `json:"embed_art_path"`
	CoverArtPath          string             `json:"cover_art_path"`
	CoverArtID            string             `json:"cover_art_id"`
	MaxYear               int32              `json:"max_year"`
	MinYear               int32              `json:"min_year"`
	Date                  string             `json:"date"`
	MaxOriginalYear       int32              `json:"max_original_year"`
	MinOriginalYear       int32              `json:"min_original_year"`
	OriginalDate          string             `json:"original_date"`
	ReleaseDate           string             `json:"release_date"`
	Compilation           bool               `json:"compilation"`
	Comment               string             `json:"comment"`
	SongCount             int32              `json:"song_count"`
	Duration              float32            `json:"duration"`
	Size                  int64              `json:"size"`
	Discs                 string             `json:"discs"`
	SortAlbumName         string             `json:"sort_album_name"`
	SortAlbumArtistName   string             `json:"sort_album_artist_name"`
	OrderAlbumName        string             `json:"order_album_name"`
	OrderAlbumArtistName  string             `json:"order_album_artist_name"`
	CatalogNum            string             `json:"catalog_num"`
	MbzAlbumID            string             `json:"mbz_album_id"`
	MbzAlbumArtistID      string             `json:"mbz_album_artist_id"`
	MbzAlbumType          string             `json:"mbz_album_type"`
	MbzAlbumComment       string             `json:"mbz_album_comment"`
	MbzReleaseGroupID     string             `json:"mbz_release_group_id"`
	FolderIds             string             `json:"folder_ids"`
	ExplicitStatus        string             `json:"explicit_status"`
	RgAlbumGain           *float64           `json:"rg_album_gain"`
	RgAlbumPeak           *float64           `json:"rg_album_peak"`
	Description           string             `json:"description"`
	SmallImageUrl         string             `json:"small_image_url"`
	MediumImageUrl        string             `json:"medium_image_url"`
	LargeImageUrl         string             `json:"large_image_url"`
	ExternalUrl           string             `json:"external_url"`
	ExternalInfoUpdatedAt pgtype.Timestamptz `json:"external_info_updated_at"`
	Genre                 string             `json:"genre"`
	Tags                  string             `json:"tags"`
	Missing               bool               `json:"missing"`
	ImportedAt            pgtype.Timestamptz `json:"imported_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type AlbumArtist struct {
	AlbumID  string `json:"album_id"`
	ArtistID string `json:"artist_id"`
	Role     string `json:"role"`
	SubRole  string `json:"sub_role"`
}

type Annotation struct {
	AnnID     string             `json:"ann_id"`
	UserID    string             `json:"user_id"`
	ItemID    string             `json:"item_id"`
	ItemType  string             `json:"item_type"`
	PlayCount *int64             `json:"play_count"`
	PlayDate  pgtype.Timestamptz `json:"play_date"`
	Rating    *int32             `json:"rating"`
	RatedAt   pgtype.Timestamptz `json:"rated_at"`
	Starred   bool               `json:"starred"`
	StarredAt pgtype.Timestamptz `json:"starred_at"`
}

type Artist struct {
	ID                    string             `json:"id"`
	Name                  string             `json:"name"`
	SortArtistName        string             `json:"sort_artist_name"`
	OrderArtistName       string             `json:"order_artist_name"`
	MbzArtistID           string             `json:"mbz_artist_id"`
	Biography             string             `json:"biography"`
	SmallImageUrl         string             `json:"small_image_url"`
	MediumImageUrl        string             `json:"medium_image_url"`
	LargeImageUrl         string             `json:"large_image_url"`
	ExternalUrl           string             `json:"external_url"`
	SimilarArtists        string             `json:"similar_artists"`
	ExternalInfoUpdatedAt pgtype.Timestamptz `json:"external_info_updated_at"`
	Missing               bool               `json:"missing"`
	UploadedImage         string             `json:"uploaded_image"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type Artwork struct {
	Hash          string             `json:"hash"`
	Mime          string             `json:"mime"`
	Width         int32              `json:"width"`
	Height        int32              `json:"height"`
	SizeBytes     int64              `json:"size_bytes"`
	BlurHash      string             `json:"blur_hash"`
	ThumbHash     string             `json:"thumb_hash"`
	DominantColor string             `json:"dominant_color"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ArtworkQueue struct {
	ItemKind   string             `json:"item_kind"`
	ItemID     string             `json:"item_id"`
	ImageType  string             `json:"image_type"`
	Priority   int32              `json:"priority"`
	Attempts   int32              `json:"attempts"`
	RetryAt    pgtype.Timestamptz `json:"retry_at"`
	EnqueuedAt pgtype.Timestamptz `json:"enqueued_at"`
}

type Folder struct {
	ID              string             `json:"id"`
	LibraryID       int32              `json:"library_id"`
	Path            string             `json:"path"`
	Name            string             `json:"name"`
	ParentID        string             `json:"parent_id"`
	NumAudioFiles   int32              `json:"num_audio_files"`
	NumPlaylists    int32              `json:"num_playlists"`
	ImageFiles      string             `json:"image_files"`
	ImagesUpdatedAt pgtype.Timestamptz `json:"images_updated_at"`
	Hash            string             `json:"hash"`
	Missing         bool               `json:"missing"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type ItemArtwork struct {
	ItemKind    string             `json:"item_kind"`
	ItemID      string             `json:"item_id"`
	ImageType   string             `json:"image_type"`
	Hash        string             `json:"hash"`
	Source      string             `json:"source"`
	SourcePath  string             `json:"source_path"`
	RefMtime    int64              `json:"ref_mtime"`
	AttemptedAt pgtype.Timestamptz `json:"attempted_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Library struct {
	ID                 int32              `json:"id"`
	Name               string             `json:"name"`
	Path               string             `json:"path"`
	RemotePath         string             `json:"remote_path"`
	LastScanAt         pgtype.Timestamptz `json:"last_scan_at"`
	LastScanStartedAt  pgtype.Timestamptz `json:"last_scan_started_at"`
	FullScanInProgress bool               `json:"full_scan_in_progress"`
	TotalSongs         int32              `json:"total_songs"`
	TotalAlbums        int32              `json:"total_albums"`
	TotalArtists       int32              `json:"total_artists"`
	TotalFolders       int32              `json:"total_folders"`
	TotalFiles         int32              `json:"total_files"`
	TotalMissingFiles  int32              `json:"total_missing_files"`
	TotalSize          int64              `json:"total_size"`
	TotalDuration      float32            `json:"total_duration"`
	DefaultNewUsers    bool               `json:"default_new_users"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type LibraryArtist struct {
	LibraryID int32  `json:"library_id"`
	ArtistID  string `json:"artist_id"`
	Stats     string `json:"stats"`
}

type MediaFile struct {
	ID                   string             `json:"id"`
	Pid                  string             `json:"pid"`
	LibraryID            int32              `json:"library_id"`
	FolderID             string             `json:"folder_id"`
	Path                 string             `json:"path"`
	Title                string             `json:"title"`
	Album                string             `json:"album"`
	Artist               string             `json:"artist"`
	ArtistID             string             `json:"artist_id"`
	AlbumArtist          string             `json:"album_artist"`
	AlbumArtistID        string             `json:"album_artist_id"`
	AlbumID              string             `json:"album_id"`
	HasCoverArt          bool               `json:"has_cover_art"`
	TrackNumber          int32              `json:"track_number"`
	DiscNumber           int32              `json:"disc_number"`
	DiscSubtitle         string             `json:"disc_subtitle"`
	Year                 int32              `json:"year"`
	Date                 string             `json:"date"`
	OriginalYear         int32              `json:"original_year"`
	OriginalDate         string             `json:"original_date"`
	ReleaseYear          int32              `json:"release_year"`
	ReleaseDate          string             `json:"release_date"`
	Size                 int64              `json:"size"`
	Suffix               string             `json:"suffix"`
	Duration             float32            `json:"duration"`
	BitRate              int32              `json:"bit_rate"`
	SampleRate           int32              `json:"sample_rate"`
	BitDepth             *int32             `json:"bit_depth"`
	Channels             int32              `json:"channels"`
	Codec                string             `json:"codec"`
	ProbeData            string             `json:"probe_data"`
	Genre                string             `json:"genre"`
	SortTitle            string             `json:"sort_title"`
	SortAlbumName        string             `json:"sort_album_name"`
	SortArtistName       string             `json:"sort_artist_name"`
	SortAlbumArtistName  string             `json:"sort_album_artist_name"`
	OrderTitle           string             `json:"order_title"`
	OrderAlbumName       string             `json:"order_album_name"`
	OrderArtistName      string             `json:"order_artist_name"`
	OrderAlbumArtistName string             `json:"order_album_artist_name"`
	Compilation          bool               `json:"compilation"`
	Comment              string             `json:"comment"`
	Lyrics               string             `json:"lyrics"`
	Bpm                  *int32             `json:"bpm"`
	ExplicitStatus       string             `json:"explicit_status"`
	CatalogNum           string             `json:"catalog_num"`
	MbzRecordingID       string             `json:"mbz_recording_id"`
	MbzReleaseTrackID    string             `json:"mbz_release_track_id"`
	MbzAlbumID           string             `json:"mbz_album_id"`
	MbzReleaseGroupID    string             `json:"mbz_release_group_id"`
	MbzArtistID          string             `json:"mbz_artist_id"`
	MbzAlbumArtistID     string             `json:"mbz_album_artist_id"`
	MbzAlbumType         string             `json:"mbz_album_type"`
	MbzAlbumComment      string             `json:"mbz_album_comment"`
	RgAlbumGain          *float64           `json:"rg_album_gain"`
	RgAlbumPeak          *float64           `json:"rg_album_peak"`
	RgTrackGain          *float64           `json:"rg_track_gain"`
	RgTrackPeak          *float64           `json:"rg_track_peak"`
	Tags                 string             `json:"tags"`
	Participants         string             `json:"participants"`
	Missing              bool               `json:"missing"`
	BirthTime            pgtype.Timestamptz `json:"birth_time"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type MediaFileArtist struct {
	MediaFileID string `json:"media_file_id"`
	ArtistID    string `json:"artist_id"`
	Role        string `json:"role"`
	SubRole     string `json:"sub_role"`
}

type Player struct {
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	UserAgent       string             `json:"user_agent"`
	UserID          string             `json:"user_id"`
	Client          string             `json:"client"`
	Ip              string             `json:"ip"`
	LastSeen        pgtype.Timestamptz `json:"last_seen"`
	TranscodingID   string             `json:"transcoding_id"`
	MaxBitRate      int32              `json:"max_bit_rate"`
	ReportRealPath  bool               `json:"report_real_path"`
	ScrobbleEnabled bool               `json:"scrobble_enabled"`
}

type Playlist struct {
	ID               string             `json:"id"`
	Name             string             `json:"name"`
	Comment          string             `json:"comment"`
	Duration         float32            `json:"duration"`
	Size             int64              `json:"size"`
	SongCount        int32              `json:"song_count"`
	OwnerID          string             `json:"owner_id"`
	Public           bool               `json:"public"`
	Path             string             `json:"path"`
	Sync             bool               `json:"sync"`
	UploadedImage    string             `json:"uploaded_image"`
	ExternalImageUrl string             `json:"external_image_url"`
	ImportedHash     string             `json:"imported_hash"`
	Rules            *string            `json:"rules"`
	EvaluatedAt      pgtype.Timestamptz `json:"evaluated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type PlaylistTrack struct {
	ID          int32  `json:"id"`
	PlaylistID  string `json:"playlist_id"`
	MediaFileID string `json:"media_file_id"`
}

type Property struct {
	ID    string `json:"id"`
	Value string `json:"value"`
}

type Radio struct {
	ID            string             `json:"id"`
	StreamUrl     string             `json:"stream_url"`
	Name          string             `json:"name"`
	HomePageUrl   string             `json:"home_page_url"`
	UploadedImage string             `json:"uploaded_image"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Scrobble struct {
	ID             int64  `json:"id"`
	MediaFileID    string `json:"media_file_id"`
	UserID         string `json:"user_id"`
	SubmissionTime int64  `json:"submission_time"`
}

type Share struct {
	ID            string             `json:"id"`
	UserID        string             `json:"user_id"`
	Description   string             `json:"description"`
	Downloadable  bool               `json:"downloadable"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	LastVisitedAt pgtype.Timestamptz `json:"last_visited_at"`
	ResourceIds   string             `json:"resource_ids"`
	ResourceType  string             `json:"resource_type"`
	Contents      string             `json:"contents"`
	Format        string             `json:"format"`
	MaxBitRate    int32              `json:"max_bit_rate"`
	VisitCount    int32              `json:"visit_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Transcoding struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	TargetFormat   string `json:"target_format"`
	Command        string `json:"command"`
	DefaultBitRate int32  `json:"default_bit_rate"`
}

type User struct {
	ID             string             `json:"id"`
	UserName       string             `json:"user_name"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	Password       string             `json:"password"`
	IsAdmin        bool               `json:"is_admin"`
	TokenEpoch     int32              `json:"token_epoch"`
	ScrobbleFilter string             `json:"scrobble_filter"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
	LastAccessAt   pgtype.Timestamptz `json:"last_access_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UserLibrary struct {
	UserID    string `json:"user_id"`
	LibraryID int32  `json:"library_id"`
}

type UserProp struct {
	UserID string `json:"user_id"`
	Key    string `json:"key"`
	Value  string `json:"value"`
}
