// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: playlist.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPlaylistTrack = `-- name: AddPlaylistTrack :exec
INSERT INTO playlist_tracks (id, playlist_id, media_file_id)
VALUES ($1, $2, $3)
ON CONFLICT (playlist_id, id) DO UPDATE SET
    media_file_id = EXCLUDED.media_file_id
`

type AddPlaylistTrackParams struct {
	ID          int32  `json:"id"`
	PlaylistID  string `json:"playlist_id"`
	MediaFileID string `json:"media_file_id"`
}

func (q *Queries) AddPlaylistTrack(ctx context.Context, arg AddPlaylistTrackParams) error {
	_, err := q.db.Exec(ctx, addPlaylistTrack, arg.ID, arg.PlaylistID, arg.MediaFileID)
	return err
}

const clearPlaylistTracks = `-- name: ClearPlaylistTracks :exec
DELETE FROM playlist_tracks
WHERE playlist_id = $1
`

func (q *Queries) ClearPlaylistTracks(ctx context.Context, playlistID string) error {
	_, err := q.db.Exec(ctx, clearPlaylistTracks, playlistID)
	return err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlist
WHERE id = $1
`

func (q *Queries) DeletePlaylist(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePlaylist, id)
	return err
}

const getPlaylistByID = `-- name: GetPlaylistByID :one
SELECT id, name, comment, duration, size, song_count, owner_id, public, path, sync, uploaded_image, external_image_url, imported_hash, rules, evaluated_at, created_at, updated_at FROM playlist
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlaylistByID(ctx context.Context, id string) (Playlist, error) {
	row := q.db.QueryRow(ctx, getPlaylistByID, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Comment,
		&i.Duration,
		&i.Size,
		&i.SongCount,
		&i.OwnerID,
		&i.Public,
		&i.Path,
		&i.Sync,
		&i.UploadedImage,
		&i.ExternalImageUrl,
		&i.ImportedHash,
		&i.Rules,
		&i.EvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlaylistTracks = `-- name: GetPlaylistTracks :many
SELECT mf.id, mf.pid, mf.library_id, mf.folder_id, mf.path, mf.title, mf.album, mf.artist, mf.artist_id, mf.album_artist, mf.album_artist_id, mf.album_id, mf.has_cover_art, mf.track_number, mf.disc_number, mf.disc_subtitle, mf.year, mf.date, mf.original_year, mf.original_date, mf.release_year, mf.release_date, mf.size, mf.suffix, mf.duration, mf.bit_rate, mf.sample_rate, mf.bit_depth, mf.channels, mf.codec, mf.probe_data, mf.genre, mf.sort_title, mf.sort_album_name, mf.sort_artist_name, mf.sort_album_artist_name, mf.order_title, mf.order_album_name, mf.order_artist_name, mf.order_album_artist_name, mf.compilation, mf.comment, mf.lyrics, mf.bpm, mf.explicit_status, mf.catalog_num, mf.mbz_recording_id, mf.mbz_release_track_id, mf.mbz_album_id, mf.mbz_release_group_id, mf.mbz_artist_id, mf.mbz_album_artist_id, mf.mbz_album_type, mf.mbz_album_comment, mf.rg_album_gain, mf.rg_album_peak, mf.rg_track_gain, mf.rg_track_peak, mf.tags, mf.participants, mf.missing, mf.birth_time, mf.created_at, mf.updated_at FROM media_file mf
JOIN playlist_tracks pt ON mf.id = pt.media_file_id
WHERE pt.playlist_id = $1
ORDER BY pt.id ASC
`

func (q *Queries) GetPlaylistTracks(ctx context.Context, playlistID string) ([]MediaFile, error) {
	rows, err := q.db.Query(ctx, getPlaylistTracks, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaFile
	for rows.Next() {
		var i MediaFile
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.LibraryID,
			&i.FolderID,
			&i.Path,
			&i.Title,
			&i.Album,
			&i.Artist,
			&i.ArtistID,
			&i.AlbumArtist,
			&i.AlbumArtistID,
			&i.AlbumID,
			&i.HasCoverArt,
			&i.TrackNumber,
			&i.DiscNumber,
			&i.DiscSubtitle,
			&i.Year,
			&i.Date,
			&i.OriginalYear,
			&i.OriginalDate,
			&i.ReleaseYear,
			&i.ReleaseDate,
			&i.Size,
			&i.Suffix,
			&i.Duration,
			&i.BitRate,
			&i.SampleRate,
			&i.BitDepth,
			&i.Channels,
			&i.Codec,
			&i.ProbeData,
			&i.Genre,
			&i.SortTitle,
			&i.SortAlbumName,
			&i.SortArtistName,
			&i.SortAlbumArtistName,
			&i.OrderTitle,
			&i.OrderAlbumName,
			&i.OrderArtistName,
			&i.OrderAlbumArtistName,
			&i.Compilation,
			&i.Comment,
			&i.Lyrics,
			&i.Bpm,
			&i.ExplicitStatus,
			&i.CatalogNum,
			&i.MbzRecordingID,
			&i.MbzReleaseTrackID,
			&i.MbzAlbumID,
			&i.MbzReleaseGroupID,
			&i.MbzArtistID,
			&i.MbzAlbumArtistID,
			&i.MbzAlbumType,
			&i.MbzAlbumComment,
			&i.RgAlbumGain,
			&i.RgAlbumPeak,
			&i.RgTrackGain,
			&i.RgTrackPeak,
			&i.Tags,
			&i.Participants,
			&i.Missing,
			&i.BirthTime,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaylists = `-- name: ListPlaylists :many
SELECT id, name, comment, duration, size, song_count, owner_id, public, path, sync, uploaded_image, external_image_url, imported_hash, rules, evaluated_at, created_at, updated_at FROM playlist
WHERE public = TRUE OR owner_id = $1
ORDER BY name ASC
`

func (q *Queries) ListPlaylists(ctx context.Context, ownerID string) ([]Playlist, error) {
	rows, err := q.db.Query(ctx, listPlaylists, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Playlist
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Comment,
			&i.Duration,
			&i.Size,
			&i.SongCount,
			&i.OwnerID,
			&i.Public,
			&i.Path,
			&i.Sync,
			&i.UploadedImage,
			&i.ExternalImageUrl,
			&i.ImportedHash,
			&i.Rules,
			&i.EvaluatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlaylist = `-- name: UpsertPlaylist :one
INSERT INTO playlist (
    id, name, comment, duration, size, song_count, owner_id,
    public, path, sync, uploaded_image, external_image_url, imported_hash,
    rules, evaluated_at, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7,
    $8, $9, $10, $11, $12, $13,
    $14, $15, $16, $17
)
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    comment = EXCLUDED.comment,
    duration = EXCLUDED.duration,
    size = EXCLUDED.size,
    song_count = EXCLUDED.song_count,
    owner_id = EXCLUDED.owner_id,
    public = EXCLUDED.public,
    path = EXCLUDED.path,
    sync = EXCLUDED.sync,
    uploaded_image = EXCLUDED.uploaded_image,
    external_image_url = EXCLUDED.external_image_url,
    imported_hash = EXCLUDED.imported_hash,
    rules = EXCLUDED.rules,
    evaluated_at = EXCLUDED.evaluated_at,
    updated_at = EXCLUDED.updated_at
RETURNING id, name, comment, duration, size, song_count, owner_id, public, path, sync, uploaded_image, external_image_url, imported_hash, rules, evaluated_at, created_at, updated_at
`

type UpsertPlaylistParams struct {
	ID               string             `json:"id"`
	Name             string             `json:"name"`
	Comment          string             `json:"comment"`
	Duration         float32            `json:"duration"`
	Size             int64              `json:"size"`
	SongCount        int32              `json:"song_count"`
	OwnerID          string             `json:"owner_id"`
	Public           bool               `json:"public"`
	Path             string             `json:"path"`
	Sync             bool               `json:"sync"`
	UploadedImage    string             `json:"uploaded_image"`
	ExternalImageUrl string             `json:"external_image_url"`
	ImportedHash     string             `json:"imported_hash"`
	Rules            *string            `json:"rules"`
	EvaluatedAt      pgtype.Timestamptz `json:"evaluated_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertPlaylist(ctx context.Context, arg UpsertPlaylistParams) (Playlist, error) {
	row := q.db.QueryRow(ctx, upsertPlaylist,
		arg.ID,
		arg.Name,
		arg.Comment,
		arg.Duration,
		arg.Size,
		arg.SongCount,
		arg.OwnerID,
		arg.Public,
		arg.Path,
		arg.Sync,
		arg.UploadedImage,
		arg.ExternalImageUrl,
		arg.ImportedHash,
		arg.Rules,
		arg.EvaluatedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Comment,
		&i.Duration,
		&i.Size,
		&i.SongCount,
		&i.OwnerID,
		&i.Public,
		&i.Path,
		&i.Sync,
		&i.UploadedImage,
		&i.ExternalImageUrl,
		&i.ImportedHash,
		&i.Rules,
		&i.EvaluatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
