// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: property.sql

package pgdb

import (
	"context"
)

const deleteProperty = `-- name: DeleteProperty :exec
DELETE FROM property
WHERE id = $1
`

func (q *Queries) DeleteProperty(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProperty, id)
	return err
}

const getProperty = `-- name: GetProperty :one
SELECT value FROM property
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProperty(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getProperty, id)
	var value string
	err := row.Scan(&value)
	return value, err
}

const putProperty = `-- name: PutProperty :exec
INSERT INTO property (id, value)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET
    value = EXCLUDED.value
`

type PutPropertyParams struct {
	ID    string `json:"id"`
	Value string `json:"value"`
}

func (q *Queries) PutProperty(ctx context.Context, arg PutPropertyParams) error {
	_, err := q.db.Exec(ctx, putProperty, arg.ID, arg.Value)
	return err
}
