// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package pgdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserLibrary = `-- name: AddUserLibrary :exec
INSERT INTO user_library (user_id, library_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddUserLibraryParams struct {
	UserID    string `json:"user_id"`
	LibraryID int32  `json:"library_id"`
}

func (q *Queries) AddUserLibrary(ctx context.Context, arg AddUserLibraryParams) error {
	_, err := q.db.Exec(ctx, addUserLibrary, arg.UserID, arg.LibraryID)
	return err
}

const clearUserLibraries = `-- name: ClearUserLibraries :exec
DELETE FROM user_library
WHERE user_id = $1
`

func (q *Queries) ClearUserLibraries(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, clearUserLibraries, userID)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM "user"
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM "user"
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const findFirstAdmin = `-- name: FindFirstAdmin :one
SELECT id, user_name, name, email, password, is_admin, token_epoch, scrobble_filter, last_login_at, last_access_at, created_at, updated_at FROM "user"
WHERE is_admin = TRUE
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) FindFirstAdmin(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, findFirstAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.TokenEpoch,
		&i.ScrobbleFilter,
		&i.LastLoginAt,
		&i.LastAccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, user_name, name, email, password, is_admin, token_epoch, scrobble_filter, last_login_at, last_access_at, created_at, updated_at FROM "user"
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.TokenEpoch,
		&i.ScrobbleFilter,
		&i.LastLoginAt,
		&i.LastAccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, user_name, name, email, password, is_admin, token_epoch, scrobble_filter, last_login_at, last_access_at, created_at, updated_at FROM "user"
WHERE LOWER(user_name) = LOWER($1) LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.TokenEpoch,
		&i.ScrobbleFilter,
		&i.LastLoginAt,
		&i.LastAccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserLibraries = `-- name: GetUserLibraries :many
SELECT l.id, l.name, l.path, l.remote_path, l.last_scan_at, l.last_scan_started_at, l.full_scan_in_progress, l.total_songs, l.total_albums, l.total_artists, l.total_folders, l.total_files, l.total_missing_files, l.total_size, l.total_duration, l.default_new_users, l.created_at, l.updated_at FROM library l
JOIN user_library ul ON l.id = ul.library_id
WHERE ul.user_id = $1
ORDER BY l.name ASC
`

func (q *Queries) GetUserLibraries(ctx context.Context, userID string) ([]Library, error) {
	rows, err := q.db.Query(ctx, getUserLibraries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Library
	for rows.Next() {
		var i Library
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.RemotePath,
			&i.LastScanAt,
			&i.LastScanStartedAt,
			&i.FullScanInProgress,
			&i.TotalSongs,
			&i.TotalAlbums,
			&i.TotalArtists,
			&i.TotalFolders,
			&i.TotalFiles,
			&i.TotalMissingFiles,
			&i.TotalSize,
			&i.TotalDuration,
			&i.DefaultNewUsers,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, user_name, name, email, password, is_admin, token_epoch, scrobble_filter, last_login_at, last_access_at, created_at, updated_at FROM "user"
ORDER BY user_name ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.UserName,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.IsAdmin,
			&i.TokenEpoch,
			&i.ScrobbleFilter,
			&i.LastLoginAt,
			&i.LastAccessAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLastAccessAt = `-- name: UpdateLastAccessAt :exec
UPDATE "user"
SET last_access_at = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateLastAccessAtParams struct {
	ID           string             `json:"id"`
	LastAccessAt pgtype.Timestamptz `json:"last_access_at"`
}

func (q *Queries) UpdateLastAccessAt(ctx context.Context, arg UpdateLastAccessAtParams) error {
	_, err := q.db.Exec(ctx, updateLastAccessAt, arg.ID, arg.LastAccessAt)
	return err
}

const updateLastLoginAt = `-- name: UpdateLastLoginAt :exec
UPDATE "user"
SET last_login_at = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateLastLoginAtParams struct {
	ID          string             `json:"id"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) UpdateLastLoginAt(ctx context.Context, arg UpdateLastLoginAtParams) error {
	_, err := q.db.Exec(ctx, updateLastLoginAt, arg.ID, arg.LastLoginAt)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO "user" (
    id, user_name, name, email, password, is_admin, token_epoch, scrobble_filter, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
ON CONFLICT (id) DO UPDATE SET
    user_name = EXCLUDED.user_name,
    name = EXCLUDED.name,
    email = EXCLUDED.email,
    password = CASE WHEN EXCLUDED.password != '' THEN EXCLUDED.password ELSE "user".password END,
    is_admin = EXCLUDED.is_admin,
    token_epoch = EXCLUDED.token_epoch,
    scrobble_filter = EXCLUDED.scrobble_filter,
    updated_at = EXCLUDED.updated_at
RETURNING id, user_name, name, email, password, is_admin, token_epoch, scrobble_filter, last_login_at, last_access_at, created_at, updated_at
`

type UpsertUserParams struct {
	ID             string             `json:"id"`
	UserName       string             `json:"user_name"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	Password       string             `json:"password"`
	IsAdmin        bool               `json:"is_admin"`
	TokenEpoch     int32              `json:"token_epoch"`
	ScrobbleFilter string             `json:"scrobble_filter"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.UserName,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.IsAdmin,
		arg.TokenEpoch,
		arg.ScrobbleFilter,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.UserName,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.IsAdmin,
		&i.TokenEpoch,
		&i.ScrobbleFilter,
		&i.LastLoginAt,
		&i.LastAccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
